"""Shared helpers for demos and starter projects."""

from .helpers import (
    AccountLike,
    ProductLike,
    StepContent,
    account_slug,
    account_status_display,
    filter_accounts,
    filter_products,
    find_account_by_slug,
    load_component_stylesheets,
    load_component_template,
    load_project_component_template,
    paginate_accounts,
    render_account_rows,
    render_feed_items,
    render_palette_detail,
    render_palette_results,
    render_signin_group,
    render_stepper_content,
    render_valid_email_group,
    sort_accounts,
    table_rows,
    toast_block,
    toast_fragment,
    validate_signin_email,
)

__all__ = [
    "AccountLike",
    "ProductLike",
    "StepContent",
    "account_slug",
    "account_status_display",
    "filter_accounts",
    "filter_products",
    "find_account_by_slug",
    "load_component_stylesheets",
    "load_component_template",
    "load_project_component_template",
    "paginate_accounts",
    "render_account_rows",
    "render_feed_items",
    "render_palette_detail",
    "render_palette_results",
    "render_signin_group",
    "render_stepper_content",
    "render_valid_email_group",
    "sort_accounts",
    "table_rows",
    "toast_block",
    "toast_fragment",
    "validate_signin_email",
]
